// ─────────────────────────────────────────────────────────────────────────────
// COSHH Recommendations - all substances
// Structure: RECOMMENDATIONS_DATA[substanceId] = { label, cats, items[] }
// Each item: { id, cat, sec, text }
// ─────────────────────────────────────────────────────────────────────────────

const RECOMMENDATIONS_DATA = {

  // ═══════════════════════════════════════════════════════════════════════════
  // FLOUR DUST
  // ═══════════════════════════════════════════════════════════════════════════
  flour: {
    label: "Flour Dust",
    cats: [
      { id: "all",    label: "All" },
      { id: "LEV",    label: "LEV" },
      { id: "Task",   label: "Task-specific" },
      { id: "RPE",    label: "RPE" },
      { id: "PPE",    label: "PPE & Skin" },
      { id: "Maint",  label: "Maintenance" },
      { id: "Clean",  label: "Cleaning" },
      { id: "Health", label: "Health surv." },
      { id: "Train",  label: "Training" },
      { id: "Exp",    label: "Exposure" },
    ],
    items: [
      // LEV & Engineering Controls
      { id: 1,  cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Install LEV at the source of dust generation for all flour handling tasks, including bag opening, tipping, dough mixing, moulding, dividing, bagging, and improver handling." },
      { id: 2,  cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "A permanent, fixed dust extraction system is the preferred option, a stand-alone mobile dust collector is acceptable only where fixed installation is not reasonably practicable." },
      { id: 3,  cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Enclose the process as much as possible - use see-through panels and plastic strip curtains to reduce open areas while maintaining safe access." },
      { id: 4,  cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Airflow velocity must be sufficient to effectively capture airborne contaminants. Adequacy will depend on hood/enclosure design, opening size, and the specific process and substance." },
      { id: 5,  cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Keep extraction ductwork as short and direct as possible, avoid long runs of flexible ducting." },
      { id: 6,  cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Position work areas away from doors, windows, and walkways to prevent draughts from disrupting LEV performance and dispersing airborne dust." },
      { id: 7,  cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Discharge extracted air to a safe external location, away from doors, windows, and fresh air inlets." },
      { id: 8,  cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Fit airflow indicators or equivalent devices on all LEV systems to allow workers to confirm the system is operating before commencing work." },
      { id: 9,  cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Fit filter blockage/failure indicator alarms to all LEV and stand-alone dust collector units." },
      { id: 10, cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Confirm LEV is switched on and functioning correctly at the start of each work period - check the gauge." },
      { id: 11, cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "For stand-alone dust collectors: the unit must not release dust on start-up and should recirculate clean air, a secondary filter meeting at least dust Type M (medium hazard) classification is required for workplace recirculation." },
      { id: 12, cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Do not allow the waste bag on stand-alone units to overfill - check gauges regularly and keep sufficient spare filters and bags on site." },
      { id: 13, cat: "LEV",    sec: "LEV & Engineering Controls",
        text: "Provide a good standard of general (dilution) ventilation throughout the work area to supplement LEV." },

      // Task-specific - FL1
      { id: 14, cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
        text: "Apply LEV with rim extraction at the tipping/mixing point, put a solid lid on the mixer where practicable." },
      { id: 15, cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
        text: "Tip flour gently - never dump. Add ingredients gently, trickle water down the inside of the bowl, and start the mixer on slow speed." },
      { id: 16, cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
        text: "When crushing empty bags, roll them up with the open end positioned within the extraction zone to capture released dust." },
      { id: 17, cat: "Task",   sec: "Task-specific - Bag Opening, Tipping & Dough Mixing (FL1)",
        text: "Consider providing mechanical or pneumatic bag/sack handling assistance to reduce manual handling and dust generation." },

      // Task-specific - FL2
      { id: 18, cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
        text: "Use LEV cabinet extraction when weighing flour improvers." },
      { id: 19, cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
        text: "Substitute high-dust improvers with low-dust alternatives wherever possible, e.g. dust-suppressed products, low-dust granules, or paste formulations." },
      { id: 20, cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
        text: "Eliminate weighing entirely where practicable by using single-dose packets." },
      { id: 21, cat: "Task",   sec: "Task-specific - Weighing & Handling Flour Improvers (FL2)",
        text: "Open improver containers with care to minimise dust release, keep used scoops and utensils inside the extraction cabinet until cleaned." },

      // Task-specific - FL3
      { id: 22, cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
        text: "Apply LEV with extraction slots at the rear of the work table, keep extraction slots free from obstructions at all times." },
      { id: 23, cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
        text: "Eliminate dusting with flour wherever possible - use non-stick table surfaces or food-grade oil as a lubricant." },
      { id: 24, cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
        text: "Where dusting cannot be avoided, workers should cast flour gently towards the extraction slots rather than across the open workspace." },
      { id: 25, cat: "Task",   sec: "Task-specific - Dough Moulding & Dividing (FL3)",
        text: "Provide easy access to remove dust build-up behind extraction slots." },

      // Task-specific - FL5
      { id: 26, cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
        text: "Apply LEV enclosing the bagging point, use a filling nozzle that directs displaced air directly into the extraction system." },
      { id: 27, cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
        text: "Ensure the filling nozzle design does not spill flour when a bag is removed." },
      { id: 28, cat: "Task",   sec: "Task-specific - Flour Bagging (FL5)",
        text: "Provide an extracted hopper at floor level to capture flour spills." },

      // Task-specific - FL6
      { id: 29, cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
        text: "Automate this task wherever technically feasible." },
      { id: 30, cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
        text: "Apply LEV enclosing the hopper feed tray." },
      { id: 31, cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
        text: "Use low-dust improver formulations (dust-suppressed products or low-dust granules), avoid weighing by using single-dose packets or whole bags wherever possible." },
      { id: 32, cat: "Task",   sec: "Task-specific - Bulk Improver Addition in Flour Milling (FL6)",
        text: "Train workers to tip additives gently into the hopper - never dump. Ensure empty bags are rolled up with the open end within the extraction zone." },

      // RPE
      { id: 33, cat: "RPE",    sec: "Respiratory Protective Equipment",
        text: "RPE with a UK Standard Assigned Protection Factor (APF) of at least 20 is required for the manual addition of bulk improvers to flour in milling operations (FL6) - this is in addition to engineering controls, not instead of them." },
      { id: 34, cat: "RPE",    sec: "Respiratory Protective Equipment",
        text: "Provide RPE for all maintenance and cleaning activities associated with flour handling equipment and LEV systems." },
      { id: 35, cat: "RPE",    sec: "Respiratory Protective Equipment",
        text: "Where tight-fitting RPE is used: face fit testing is mandatory, workers must be clean-shaven, train workers in correct donning, doffing, and pre-use checks.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 36, cat: "RPE",    sec: "Respiratory Protective Equipment",
        text: "Disposable RPE must be discarded at the end of each shift, or sooner if it becomes blocked." },
      { id: 37, cat: "RPE",    sec: "Respiratory Protective Equipment",
        text: "Replace reusable respirator filters in accordance with manufacturer guidance and whenever filters are past shelf-life, visibly damaged or contaminated, or breathing resistance increases." },
      { id: 38, cat: "RPE",    sec: "Respiratory Protective Equipment",
        text: "Carry out RPE examination and testing at least monthly (or before each use if infrequent - intervals must not exceed three months)." },
      { id: 39, cat: "RPE",    sec: "Respiratory Protective Equipment",
        text: "Where RPE is required for periods exceeding one hour, provide powered air-purifying respirators (PAPR) or constant-flow airline breathing apparatus." },
      { id: 40, cat: "RPE",    sec: "Respiratory Protective Equipment",
        text: "Keep all RPE clean and store in a clean, designated location when not in use." },

      // PPE & Skin
      { id: 41, cat: "PPE",    sec: "PPE & Skin Protection",
        text: "Provide coveralls that do not retain dust, arrange laundering through a contract laundry service - workers must not launder work clothing at home." },
      { id: 42, cat: "PPE",    sec: "PPE & Skin Protection",
        text: "Provide warm water, mild skin cleansers, and soft paper or fabric towels at all wash stations - avoid abrasive cleansers." },
      { id: 43, cat: "PPE",    sec: "PPE & Skin Protection",
        text: "Provide pre-work emollient skin creams to facilitate post-work skin cleansing." },
      { id: 44, cat: "PPE",    sec: "PPE & Skin Protection",
        text: "Provide after-work emollient creams to replenish skin lipids following handwashing." },
      { id: 45, cat: "PPE",    sec: "PPE & Skin Protection",
        text: "Note: barrier creams do not constitute a complete physical barrier and must not be used as a substitute for other protective measures." },

      // Maintenance
      { id: 46, cat: "Maint",  sec: "Maintenance, Examination & Testing",
        text: "LEV systems are subject to a statutory Thorough Examination and Test (TExT) under COSHH Regulation 9, this must be carried out by a competent person at intervals not exceeding 14 months.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 47, cat: "Maint",  sec: "Maintenance, Examination & Testing",
        text: "Carry out a visual check of all control equipment for signs of damage or deterioration before commencing work each day." },
      { id: 48, cat: "Maint",  sec: "Maintenance, Examination & Testing",
        text: "Maintain a LEV user manual or log book recording performance specifications, inspection frequency, maintenance schedules, and parts replacement history." },
      { id: 49, cat: "Maint",  sec: "Maintenance, Examination & Testing",
        text: "Retain records of all LEV examinations and tests for a minimum of 5 years." },
      { id: 50, cat: "Maint",  sec: "Maintenance, Examination & Testing",
        text: "Act on all remedial actions identified by TExT reports without undue delay." },
      { id: 51, cat: "Maint",  sec: "Maintenance, Examination & Testing",
        text: "Verify the effectiveness of controls using qualitative dust lamp (Tyndall beam) checks.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },

      // Cleaning
      { id: 52, cat: "Clean",  sec: "Cleaning & Housekeeping",
        text: "Clean work equipment and the immediate work area at the end of each shift (daily minimum)." },
      { id: 53, cat: "Clean",  sec: "Cleaning & Housekeeping",
        text: "Clean the wider workroom, including overhead beams, heating pipework, and light fittings, at least once per week." },
      { id: 54, cat: "Clean",  sec: "Cleaning & Housekeeping",
        text: "Remove dry flour dust by vacuum cleaning or wet methods only - vacuum equipment must meet at least dust Class M (medium hazard) classification." },
      { id: 55, cat: "Clean",  sec: "Cleaning & Housekeeping",
        text: "Deal with flour spills immediately, shovel large spills carefully into a waste bag or spill hopper." },
      { id: 56, cat: "Clean",  sec: "Cleaning & Housekeeping",
        text: "Never use brushes or compressed air to remove dust from clothing, skin, or equipment surfaces - these methods disperse dust into the breathing zone." },

      // Health Surveillance
      { id: 57, cat: "Health", sec: "Health Surveillance",
        text: "Implement a health surveillance programme for occupational asthma where there is a reasonable likelihood of it developing. Surveillance must be conducted under the supervision of a doctor or occupational health professional and should include pre-placement baseline assessment, periodic symptom questionnaires, and lung function testing (spirometry).",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 58, cat: "Health", sec: "Health Surveillance",
        text: "Implement a health surveillance programme for occupational dermatitis where there is a reasonable likelihood of it developing. Surveillance should include pre-placement skin assessment and regular periodic skin inspections by a trained responsible person, with referral to occupational health if symptoms are identified.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 59, cat: "Health", sec: "Health Surveillance",
        text: "Inform workers of the early signs and symptoms of occupational asthma and contact dermatitis and advise them to report any symptoms to their line manager promptly." },

      // Training
      { id: 60, cat: "Train",  sec: "Training & Supervision",
        text: "Permit access to flour handling areas to authorised and appropriately trained personnel only." },
      { id: 61, cat: "Train",  sec: "Training & Supervision",
        text: "Provide documented training covering: health hazards of flour dust and enzyme improvers, correct use and checking of LEV, correct use, maintenance, and storage of RPE and PPE, and actions in the event of control failure." },
      { id: 62, cat: "Train",  sec: "Training & Supervision",
        text: "Maintain training records as evidence that training has been delivered and understood." },
      { id: 63, cat: "Train",  sec: "Training & Supervision",
        text: "Review and update training whenever work processes, substances, or LEV systems change." },
      { id: 64, cat: "Train",  sec: "Training & Supervision",
        text: "Include managers and supervisors in all relevant health and safety training." },
      { id: 65, cat: "Train",  sec: "Training & Supervision",
        text: "Provide active supervision to ensure safe work procedures are consistently followed." },

      // Exposure
      { id: 66, cat: "Exp",    sec: "Occupational Exposure Benchmark",
        text: "When all COSHH controls are correctly implemented, flour dust concentrations of less than 2 mg/m\u00b3 (8-hour TWA) should be achievable at all assessed tasks." },
      { id: 67, cat: "Exp",    sec: "Occupational Exposure Benchmark",
        text: "Where monitoring results exceed 2 mg/m\u00b3 TWA, controls should be reviewed and remedial actions implemented before re-sampling." },
      { id: 68, cat: "Exp",    sec: "Occupational Exposure Benchmark",
        text: "The Workplace Exposure Limit (WEL) for flour dust is 10 mg/m\u00b3 (8-hr TWA), the HSE recommends exposure be reduced as far below the WEL as reasonably practicable - 2 mg/m\u00b3 represents good control practice performance." },
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METALWORKING FLUIDS
  // Sources: MW1 (CNC machining), MW2 (skin risks), MW3 (sump cleaning:
  //          water-mix), MW4 (sump cleaning: neat oils), MW5 (fluid quality)
  // ═══════════════════════════════════════════════════════════════════════════
  mwf: {
    label: "Metalworking Fluids",
    cats: [
      { id: "all",    label: "All" },
      { id: "LEV",    label: "LEV & Engineering" },
      { id: "Fluid",  label: "Fluid Management" },
      { id: "Sump",   label: "Sump Cleaning" },
      { id: "RPE",    label: "RPE" },
      { id: "PPE",    label: "PPE & Skin" },
      { id: "Maint",  label: "Maintenance" },
      { id: "Clean",  label: "Cleaning" },
      { id: "Health", label: "Health surv." },
      { id: "Train",  label: "Training" },
    ],
    items: [

      // ── LEV & Engineering Controls (MW1) ───────────────────────────────────
      { id: 1,  cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Permit access to machining areas to authorised and appropriately trained personnel only." },
      { id: 2,  cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Apply MWF at the lowest possible pressure and flow volume consistent with adequate lubrication, cooling, and swarf removal." },
      { id: 3,  cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Apply MWF at the point where the tool and workpiece make contact, to minimise mist generation from contact with other rotating parts." },
      { id: 4,  cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Stop MWF delivery when not machining, maintain fluid circulation to prevent stagnation." },
      { id: 5,  cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Enclose CNC machines as much as possible - for example by retrofitting roof panels - to contain mist within the enclosure." },
      { id: 6,  cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Provide LEV to the machine enclosure, either as a standalone unit or a centralised system linking two or more machines. Design considerations must include volume flow rate, location of extraction points, enclosure volume and dimensions, and the level of mist generated." },
      { id: 7,  cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Discharge extracted air to a safe place outside the building, away from doors, windows, and air inlets. Where extracted air is recirculated into the workshop, a suitable high-efficiency air cleaning device must be in place." },
      { id: 8,  cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Provide an easy means of confirming the LEV is working before commencing work, such as an airflow indicator or equivalent device." },
      { id: 9,  cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Observe a time delay between the machine stopping and opening the enclosure doors, to ensure no mist is present in the operator's breathing zone. The required delay can be established using a smoke test or dust lamp, and implemented via the machine programme or a timer." },
      { id: 10, cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Consider alternatives to compressed air guns for cleaning components and machine surfaces - such as vacuum guns, absorbent materials, low-pressure coolant guns, spindle-mounted fans, or automatic compressed air hoses operated with enclosure doors shut." },
      { id: 11, cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Where compressed air guns cannot be avoided: reduce exit pressure to as low as practicable (30 psi / 2.1 bar is effective for cleaning), use nozzle designs that allow lower operating pressure, blow down components inside the machine enclosure with LEV running, and consider guns with longer lances (e.g. 30 cm)." },
      { id: 12, cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Never use compressed air for cleaning skin or clothing." },
      { id: 13, cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Use suitable swarf vacuums to remove wet swarf and chips from machine surfaces." },
      { id: 14, cat: "LEV",   sec: "LEV & Engineering Controls - CNC Machining (MW1)",
        text: "Finished components may be cleaned in industrial washing or degreasing machines as an alternative to compressed air." },

      // ── Fluid Management & Skin Risk (MW2) ────────────────────────────────
      { id: 15, cat: "Fluid", sec: "Fluid Management & Skin Risk Reduction (MW2)",
        text: "Review MWF selection with a view to substituting current fluids with products that have less hazardous components - for example, fluids free from formaldehyde-releasing biocides, lower dermal sensitiser content, or reduced misting potential." },
      { id: 16, cat: "Fluid", sec: "Fluid Management & Skin Risk Reduction (MW2)",
        text: "Minimise leaks of tramp oil (hydraulic, lubricating, or gearbox oil) into the sump. Remove tramp oil using mechanical skimmers, mobile oil coalescers, or vacuum systems." },
      { id: 17, cat: "Fluid", sec: "Fluid Management & Skin Risk Reduction (MW2)",
        text: "Remove metal fines from the fluid using centrifuges, filtration systems, or magnetic separators for ferrous materials." },
      { id: 18, cat: "Fluid", sec: "Fluid Management & Skin Risk Reduction (MW2)",
        text: "Mix fresh water-mix fluids to the supplier's recommended concentration. Top up only with fluid below the recommended concentration, as fluids in use evaporate and become more concentrated." },
      { id: 19, cat: "Fluid", sec: "Fluid Management & Skin Risk Reduction (MW2)",
        text: "Do not add biocide until all good practice measures to maintain fluid quality have been followed. If biocide is needed, add the correct amount directly to the sump. Higher than recommended fluid or biocide concentration increases the risk of skin disease." },
      { id: 20, cat: "Fluid", sec: "Fluid Management & Skin Risk Reduction (MW2)",
        text: "Prevent skin contact with MWF wherever possible. Where this is not practicable, use splash guards and limit the extent and duration of contact." },
      { id: 21, cat: "Fluid", sec: "Fluid Management & Skin Risk Reduction (MW2)",
        text: "Use automatic mixing devices for water-mix fluids instead of manual mixing." },
      { id: 22, cat: "Fluid", sec: "Fluid Management & Skin Risk Reduction (MW2)",
        text: "Where machines are not fully enclosed, provide properly designed splash guards - do not use rags or plastic sheeting as substitutes." },
      { id: 23, cat: "Fluid", sec: "Fluid Management & Skin Risk Reduction (MW2)",
        text: "Use appropriate tools such as brushes, magnetic wands, and swarf hooks to remove swarf and chips from machine surfaces and components. Never remove swarf or fines from the sump by hand - use brushes and shovels, and wear cut-resistant gloves only when machinery is switched off." },

      // ── Fluid Quality Management (MW5) ────────────────────────────────────
      { id: 24, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Cover sumps to keep them free from contamination such as food waste, teabags, and other foreign material." },
      { id: 25, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Prevent fluid stagnation in sumps and pipes - keep fluid circulating using pumps. When commissioning or modifying a MWF supply system, avoid dead-ends and dead-legs that restrict flow." },
      { id: 26, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Remove dead-ends from pipework, where dead-legs cannot be eliminated, minimise risk by regular flushing (e.g. weekly)." },
      { id: 27, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Check all strainers and filters regularly for blockages." },
      { id: 28, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Check the fluid appearance every day for unusual odour or biofilm deposits inside the sump." },
      { id: 29, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Check weekly that tramp oil content is kept below 2%. Measure fluid concentration (using a refractometer) and pH at least weekly, and follow the supplier's recommended ranges." },
      { id: 30, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Measure sump fluid temperature weekly. Consider cooling the fluid if its temperature rises significantly above workroom temperature." },
      { id: 31, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Monitor fluid for bacteria using weekly dipslide testing. Stir the sump before testing to avoid tramp oil coating the slide, and use a dipslide incubator at consistent temperature. Follow the supplier's instructions for incubation time and temperature." },
      { id: 32, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Dipslide results at or above 10\u2074 cfu/ml indicate microbial growth - review all fluid management practices before considering biocide addition. Dipslide results at or above 10\u2076 cfu/ml indicate poor control, act immediately, which will normally mean draining and cleaning the system." },
      { id: 33, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "If biocide addition is required, use only at doses recommended by the supplier. Use a dispensing system where practicable and add at a point of high turbulence such as the sump to ensure complete mixing." },
      { id: 34, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Check input water quality for hardness, pH, and bacteria. If using stored rather than mains water, carry out weekly inspections of water storage tanks and filtration equipment." },
      { id: 35, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Keep records of all fluid quality tests (dipslide, concentration, pH, tramp oil, temperature) for at least five years. Record results in a table or graph to identify trends and support timely action." },
      { id: 36, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Where a third party carries out fluid quality checks, ensure the results and any remedial actions taken are reviewed internally." },
      { id: 37, cat: "Fluid", sec: "Fluid Quality Management (MW5)",
        text: "Train all staff who carry out fluid quality monitoring on the equipment to be used, correct procedures, recording and interpreting results, and the remedial actions to take." },

      // ── Sump Cleaning - Water-mix Fluids (MW3) ────────────────────────────
      { id: 38, cat: "Sump",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
        text: "Establish a sump cleaning schedule based on visual inspection, fluid monitoring results, and your supplier's guidance." },
      { id: 39, cat: "Sump",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
        text: "Use suitable equipment to remove and replace sump fluids with minimum spillage (e.g. a wet vacuum). Ensure the sump is cleaned before adding fresh MWF." },
      { id: 40, cat: "Sump",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
        text: "Avoid using high-pressure water hoses for sump cleaning where practicable, as this generates mist." },
      { id: 41, cat: "Sump",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
        text: "Keep absorbent material to hand in case of spillages during sump cleaning." },
      { id: 42, cat: "Sump",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
        text: "Follow the sump cleaning procedure: add system cleaner and circulate for the specified time, drain and clean out liquid and swarf, clean all hose connections, filters, splash screens, and tramp oil separators, refill with fresh water-mix MWF at the supplier's recommended concentration, leave for one week then test with a dipslide - if bacteria are below 10,000 cfu/ml, resume use." },
      { id: 43, cat: "Sump",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
        text: "For heavily contaminated machines, follow a second cleaning cycle using a further system cleaner in warm water before refilling." },
      { id: 44, cat: "Sump",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
        text: "Cleaning a large enclosed sump or underfloor tank may create a confined space risk. Before carrying out such work, complete a confined space risk assessment, implement a permit-to-work system, ensure a trained attendant is present outside the space, and have emergency rescue arrangements in place. Air-fed RPE must be used inside the confined space." },
      { id: 45, cat: "Sump",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
        text: "RPE with a UK Standard APF of at least 20 (e.g. FFP3 or powered TH2) is required during sump cleaning where mist is generated, for example when using a high-pressure water hose." },
      { id: 46, cat: "Sump",  sec: "Sump Cleaning - Water-mix Fluids (MW3)",
        text: "If RPE is required for extended periods (more than 1 hour continuously), use powered respirators or breathing apparatus. For confined space sump cleaning, air-fed RPE must be used." },

      // ── Sump Cleaning - Neat Oils (MW4) ───────────────────────────────────
      { id: 47, cat: "Sump",  sec: "Sump Cleaning - Neat Oils (MW4)",
        text: "Establish a neat oil sump cleaning schedule based on regular visual inspection and fluid condition monitoring. Use a wet vacuum or pump to remove and replace oil with minimum spillage." },
      { id: 48, cat: "Sump",  sec: "Sump Cleaning - Neat Oils (MW4)",
        text: "Follow the neat oil sump cleaning procedure: drain the oil from the sump and supply system, if contaminated, flush with a compatible neat flushing oil, circulate for the supplier's recommended time, operate all ancillary equipment, check flow rates and system integrity, then drain and repair any defective parts before refilling with new neat oil." },
      { id: 49, cat: "Sump",  sec: "Sump Cleaning - Neat Oils (MW4)",
        text: "Provide suitable skin and eye protection for all neat oil sump cleaning tasks - chemical- and cut-resistant gloves (only when machinery is switched off), goggles or safety glasses, and overalls covering the forearms." },
      { id: 50, cat: "Sump",  sec: "Sump Cleaning - Neat Oils (MW4)",
        text: "Dispose of drained neat oil safely in accordance with environmental regulations - do not return spilt or drained oil to the machine, as this contaminates the system." },

      // ── RPE ───────────────────────────────────────────────────────────────
      { id: 51, cat: "RPE",   sec: "Respiratory Protective Equipment",
        text: "Ensure LEV and enclosure controls are sufficiently effective that RPE is not required as a routine control during CNC machining. Where monitoring or visual checks indicate controls are inadequate, provide RPE with a UK Standard APF of at least 20 until controls are remediated." },
      { id: 52, cat: "RPE",   sec: "Respiratory Protective Equipment",
        text: "Provide RPE with a UK Standard APF of at least 20 (e.g. FFP3 disposable or powered TH2) where mist is generated and engineering controls alone cannot adequately control exposure, including during water-mix sump cleaning where a high-pressure hose is used." },
      { id: 53, cat: "RPE",   sec: "Respiratory Protective Equipment",
        text: "Where tight-fitting RPE is used: face fit testing is mandatory, workers must be clean-shaven, provide training in correct donning, doffing, and pre-use checks.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 54, cat: "RPE",   sec: "Respiratory Protective Equipment",
        text: "Disposable RPE must be discarded at the end of each shift, or sooner if it becomes blocked." },
      { id: 55, cat: "RPE",   sec: "Respiratory Protective Equipment",
        text: "Replace reusable respirator filters in accordance with manufacturer guidance, and whenever filters are past shelf-life, visibly damaged or contaminated, or breathing resistance increases." },
      { id: 56, cat: "RPE",   sec: "Respiratory Protective Equipment",
        text: "Carry out thorough examination and testing of non-disposable RPE at least monthly. Check all RPE is functioning correctly before each use." },
      { id: 57, cat: "RPE",   sec: "Respiratory Protective Equipment",
        text: "Where RPE is required for extended periods (more than 1 hour continuously), provide powered respirators or breathing apparatus." },
      { id: 58, cat: "RPE",   sec: "Respiratory Protective Equipment",
        text: "Where airline breathing apparatus is used, check the quality of the air supply at least every three months, and more frequently where air quality cannot be assured. Visually inspect compressed airline hoses for damage before each use." },
      { id: 59, cat: "RPE",   sec: "Respiratory Protective Equipment",
        text: "Keep all RPE clean and store it in a clean, designated location when not in use." },

      // ── PPE & Skin ────────────────────────────────────────────────────────
      { id: 60, cat: "PPE",   sec: "PPE & Skin Protection",
        text: "Select PPE appropriate to the task: single-use nitrile gloves for routine machining where skin contact cannot be avoided (provided entanglement risk is low), thicker chemical-resistant gloves for cleaning and maintenance, goggles or safety glasses for all tasks involving fluid splash risk, and coveralls covering the forearms." },
      { id: 63, cat: "PPE",   sec: "PPE & Skin Protection",
        text: "Replace gloves at recommended intervals and discard damaged gloves immediately. Make suitable arrangements for maintenance, storage, and replacement of all PPE." },
      { id: 65, cat: "PPE",   sec: "PPE & Skin Protection",
        text: "Provide overalls that cover the forearms. Ensure contaminated overalls are laundered before re-use - use a contract laundry service, workers must not launder work clothing at home." },
      { id: 66, cat: "PPE",   sec: "PPE & Skin Protection",
        text: "Remove clothing contaminated with MWF immediately to reduce skin contact." },
      { id: 67, cat: "PPE",   sec: "PPE & Skin Protection",
        text: "Provide warm water, mild skin cleansers, and soft paper or fabric towels at all wash stations. Wash hands after any contact with MWF. Avoid abrasive cleansers." },
      { id: 68, cat: "PPE",   sec: "PPE & Skin Protection",
        text: "Provide pre-work emollient creams to make it easier to remove contamination from the skin after work." },
      { id: 69, cat: "PPE",   sec: "PPE & Skin Protection",
        text: "Provide after-work emollient creams to restore the natural moisture content of the skin following washing." },
      { id: 70, cat: "PPE",   sec: "PPE & Skin Protection",
        text: "Do not use pre-work or 'barrier' creams as a substitute for gloves or other engineering controls - they do not provide a full physical barrier and must only be used alongside appropriate PPE." },

      // ── Maintenance, Examination & Testing ────────────────────────────────
      { id: 71, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Keep all LEV equipment in effective and efficient working order, maintained in accordance with the supplier's or installer's guidance." },
      { id: 72, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Before starting work each day, check for swarf and chips accumulating around extraction points and confirm that airflow indicators are showing correct airflow." },
      { id: 73, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Carry out weekly checks of flexible ducts and filter housings for signs of damage or deterioration." },
      { id: 74, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Repair faulty extraction systems promptly - do not allow defective LEV to remain in service." },
      { id: 75, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Maintain an LEV user manual and logbook containing operating specifications, maintenance schedules, records of all checks and repairs, and a list of known failure modes. If the system was installed without documentation, commission a competent person to carry out a system assessment and produce a commissioning report before the system is relied upon for exposure control." },
      { id: 76, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "LEV systems require a statutory Thorough Examination and Test (TExT) carried out by a competent person at least every 14 months. Carry out all remedial actions arising from TExT reports and retain records for at least 5 years.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 77, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Verify the effectiveness of LEV controls using a dust lamp or direct-reading aerosol monitor to identify leaks and areas of high mist concentration.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 78, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Implement a documented fluid quality monitoring programme covering daily visual checks, weekly measurements of concentration, pH, tramp oil content, and temperature, and weekly dipslide testing for bacterial contamination. Act on results promptly to maintain fluid within the supplier's recommended parameters." },

      // ── Cleaning & Housekeeping ────────────────────────────────────────────
      { id: 79, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Keep all surfaces clean to minimise skin contact with MWF." },
      { id: 80, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Deal with fluid spills immediately - contain leaks and use a wet vacuum or suitable oil-absorbent granules or pads to recover residues. Do not use sawdust or loose materials that may spread contamination. Dispose of waste in sealed containers in accordance with environmental regulations." },
      { id: 81, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Dispose of spilt MWF safely - do not return spilt fluid to the machine sump, as this contaminates the system and reduces the operational life of the fluid." },
      { id: 82, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Provide clean welfare facilities for washing and taking refreshment, located away from all machining activities." },

      // ── Health Surveillance ────────────────────────────────────────────────
      { id: 83, cat: "Health", sec: "Health Surveillance",
        text: "Implement a health surveillance programme for occupational asthma where workers are regularly exposed to MWF mists. Surveillance must be conducted under the supervision of a doctor or occupational health professional and should include pre-placement baseline assessment, periodic symptom questionnaires, and lung function testing (spirometry).",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 84, cat: "Health", sec: "Health Surveillance",
        text: "Implement a health surveillance programme for occupational dermatitis where workers have regular skin contact with MWF. Surveillance should include pre-placement skin assessment and regular periodic skin inspections by a trained responsible person, with referral to occupational health if symptoms are identified.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 85, cat: "Health", sec: "Health Surveillance",
        text: "Inform workers of the early signs and symptoms of occupational asthma, occupational hypersensitivity pneumonitis, and contact dermatitis. Advise them to report any symptoms to their line manager promptly and to co-operate with health surveillance." },
      { id: 86, cat: "Health", sec: "Health Surveillance",
        text: "Advise workers to check their skin regularly for dryness or soreness and to report any such symptoms to their supervisor without delay." },

      // ── Training & Supervision ────────────────────────────────────────────
      { id: 87, cat: "Train", sec: "Training & Supervision",
        text: "Permit access to machining areas to authorised and appropriately trained personnel only." },
      { id: 88, cat: "Train", sec: "Training & Supervision",
        text: "Provide documented training covering: health hazards of MWF mist and skin contact, correct use, checking, and limitations of LEV, when and how to use alternatives to compressed air guns, correct use, maintenance, and storage of RPE and PPE (including correct donning and doffing of gloves), and actions to take in the event of a control failure or fluid spill." },
      { id: 89, cat: "Train", sec: "Training & Supervision",
        text: "Maintain training records as evidence that training has been delivered and understood." },
      { id: 90, cat: "Train", sec: "Training & Supervision",
        text: "Include managers and supervisors in all relevant health and safety training." },
      { id: 91, cat: "Train", sec: "Training & Supervision",
        text: "Provide active supervision to ensure safe work procedures are consistently followed." },
    ]
  },


  // ═══════════════════════════════════════════════════════════════════════════
  // WELDING, HOT WORK AND ALLIED PROCESSES
  // Sources: WL2 (confined spaces), WL3 (welding fume/LEV/general ventilation),
  //          WL14 (manual gas/oxy-gas cutting), WL15 (plasma arc - fixed),
  //          WL16 (arc-air gouging), WL18 (pressure blasting - small items),
  //          WL19 (pressure blasting - medium items),
  //          WL20 (pressure blasting - large items),
  //          WL21 (weld cleaning with pickling paste)
  // ═══════════════════════════════════════════════════════════════════════════
  welding: {
    label: "Welding & Hot Work",
    cats: [
      { id: "all",      label: "All" },
      { id: "Eng",      label: "Engineering" },
      { id: "RPE",      label: "RPE" },
      { id: "PPE",      label: "PPE & Skin" },
      { id: "Confined", label: "Confined spaces" },
      { id: "Blast",    label: "Blasting" },
      { id: "Pickling", label: "Pickling paste" },
      { id: "Maint",    label: "Maintenance" },
      { id: "Clean",    label: "Cleaning" },
      { id: "Health",   label: "Health surv." },
      { id: "Train",    label: "Training" },
    ],
    items: [

      // Engineering Controls - Welding Fume (WL3)
      { id: 1,  cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Permit access to welding and hot work areas to authorised and appropriately trained personnel only." },
      { id: 2,  cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Before welding, design the job to minimise the amount of welding required - consider cold joining techniques, mechanical fasteners, thinner gauge metal, or adhesive bonding where appropriate." },
      { id: 3,  cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Remove all grease and surface coatings before welding. Paint and resin coatings release toxic components when heated, significantly increasing fume hazard." },
      { id: 4,  cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Position the workpiece and LEV hood so that rising fume is drawn away from the welder's breathing zone rather than through it." },
      { id: 5,  cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Select the most appropriate LEV design for the welding process and workpiece size. The hood design is critical - it determines how effectively fume is captured. Ensure all elements of the system are matched to the process requirements." },
      { id: 6,  cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "For small to medium workpieces, use an extracted bench or extracted booth that draws fume away from the welder towards an air inlet at the rear. Keep the work surface free from clutter to avoid restricting airflow, and enclose as much of the bench as practicable to prevent cross-draughts." },
      { id: 7,  cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Ensure the workpiece is positioned correctly within the booth so that fume is captured effectively. A turntable or bespoke jig can assist with optimal positioning." },
      { id: 8,  cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "For MIG welding on large or extra-large workpieces, use on-torch extraction as the primary control - the extraction is integrated with the welding gun, moves with the weld, and maintains close proximity to the source at all times." },
      { id: 9,  cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Be aware of the limitations of on-torch extraction: it is less effective for fillet welding or overhead groove welding, and is not always practical when working at height. Where on-torch extraction is not suitable, use LEV with a movable fume capture hood on a flexible extraction arm." },
      { id: 10, cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Position movable fume capture hoods within one hood diameter of the welding point. Mark the capture zone as a visual guide and reposition the hood as frequently as necessary to maintain effective fume capture throughout the weld run." },
      { id: 11, cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Ensure LEV ducting is free from acute bends, kinks, holes, and cracks, and avoid long runs of flexible ducting." },
      { id: 12, cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Fit a suitable filter for welding fume in the extraction unit. Fit an indicator or alarm to show when the filter has blocked or failed, and inspect and replace filters regularly." },
      { id: 13, cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Discharge extracted air outside the building to a safe location away from doors, windows, and air inlets. Where recirculation into the workshop is unavoidable, ensure the extracted air is thoroughly cleaned by high-efficiency filtration before return." },
      { id: 14, cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Provide an airflow indicator or equivalent device on all LEV systems to allow workers to confirm the system is operating correctly before starting work." },
      { id: 15, cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "Provide mechanical general ventilation (fans mounted in the ceiling or high on walls) throughout all indoor welding workshops. Natural ventilation from open doors and windows is not sufficient to disperse welding fume in most situations." },
      { id: 16, cat: "Eng", sec: "Engineering Controls - Welding Fume (WL3)",
        text: "When welding tasks must be carried out outdoors or at height where LEV is not reasonably practicable, provide RPE to all workers in the area who may be exposed to fume, and ensure good general ventilation is in place to prevent fume lingering." },

      // Engineering Controls - Manual Gas / Oxy-gas Cutting (WL14)
      { id: 18, cat: "Eng", sec: "Engineering Controls - Manual Gas & Oxy-gas Cutting (WL14)",
        text: "Provide a good standard of general ventilation in all areas where gas and oxy-gas cutting is carried out." },
      { id: 19, cat: "Eng", sec: "Engineering Controls - Manual Gas & Oxy-gas Cutting (WL14)",
        text: "Consider automating gas cutting tasks of long duration to reduce operator exposure." },
      { id: 20, cat: "Eng", sec: "Engineering Controls - Manual Gas & Oxy-gas Cutting (WL14)",
        text: "Position the workpiece so that the operator's head is out of the rising cutting fume at all times." },
      { id: 21, cat: "Eng", sec: "Engineering Controls - Manual Gas & Oxy-gas Cutting (WL14)",
        text: "Remove all grease and surface coatings from the metal before cutting." },
      { id: 22, cat: "Eng", sec: "Engineering Controls - Manual Gas & Oxy-gas Cutting (WL14)",
        text: "Purge gas hoses to ensure no residual gas is present before lighting the flame." },
      { id: 23, cat: "Eng", sec: "Engineering Controls - Manual Gas & Oxy-gas Cutting (WL14)",
        text: "Fit flashback arrestors to both cylinders when using oxy-acetylene cutting equipment." },
      { id: 24, cat: "Eng", sec: "Engineering Controls - Manual Gas & Oxy-gas Cutting (WL14)",
        text: "Check that gas cylinder regulators are correctly connected and are not leaking before starting work." },
      { id: 25, cat: "Eng", sec: "Engineering Controls - Manual Gas & Oxy-gas Cutting (WL14)",
        text: "Site the cutting work area away from doors, windows, and walkways to prevent the spread of airborne fume to other parts of the workplace." },

      // Engineering Controls - Plasma Arc Cutting (WL15)
      { id: 26, cat: "Eng", sec: "Engineering Controls - Plasma Arc Cutting: Fixed Equipment (WL15)",
        text: "Use a mechanised plasma cutter within a water bath so that cutting takes place submerged under water, suppressing fume generation at source." },
      { id: 27, cat: "Eng", sec: "Engineering Controls - Plasma Arc Cutting: Fixed Equipment (WL15)",
        text: "Provide LEV around the plasma torch above the water level to capture any residual fume not suppressed by the water bath." },
      { id: 28, cat: "Eng", sec: "Engineering Controls - Plasma Arc Cutting: Fixed Equipment (WL15)",
        text: "Verify that corrosion inhibitors added to the water bath do not generate hazardous fumes during the cutting process." },
      { id: 29, cat: "Eng", sec: "Engineering Controls - Plasma Arc Cutting: Fixed Equipment (WL15)",
        text: "Clean out water baths regularly. When cutting aluminium alloys, metal deposition and dross accumulation can generate hydrogen - increase cleaning frequency accordingly." },
      { id: 30, cat: "Eng", sec: "Engineering Controls - Plasma Arc Cutting: Fixed Equipment (WL15)",
        text: "Remove all grease and surface coatings from the material before cutting." },
      { id: 31, cat: "Eng", sec: "Engineering Controls - Plasma Arc Cutting: Fixed Equipment (WL15)",
        text: "Where in-air plasma cutting is used instead of a water bath, provide an under-table extraction system to capture fume and protect workers from the arc." },
      { id: 32, cat: "Eng", sec: "Engineering Controls - Plasma Arc Cutting: Fixed Equipment (WL15)",
        text: "Site the cutting work area away from doors, windows, and walkways to prevent draughts from interfering with LEV performance and spreading airborne fume." },

      // Engineering Controls - Arc-air Gouging (WL16)
      { id: 33, cat: "Eng", sec: "Engineering Controls - Arc-air Gouging (WL16)",
        text: "Isolate arc-air gouging from the general workforce by carrying out all work in an enclosed extracted booth or a segregated area with dedicated LEV." },
      { id: 34, cat: "Eng", sec: "Engineering Controls - Arc-air Gouging (WL16)",
        text: "Fit an airflow indicator or equivalent device on the booth extraction system. Confirm that extraction is switched on and functioning correctly at the start of every work period." },
      { id: 35, cat: "Eng", sec: "Engineering Controls - Arc-air Gouging (WL16)",
        text: "Discharge extracted air to a safe location away from doors, windows, and air inlets." },
      { id: 36, cat: "Eng", sec: "Engineering Controls - Arc-air Gouging (WL16)",
        text: "Position work to keep the operator's head out of the fume plume at all times." },

      // RPE
      { id: 38, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "For regular or high-intensity MMA, FCA, or MIG/MAG welding, provide LEV and supplementary RPE with an APF of at least 20. RPE is also required where the size or shape of the workpiece means LEV cannot provide reliable and consistent fume capture for all welds." },
      { id: 39, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "For welding tasks requiring RPE for more than 1 hour per day, provide a powered air-purifying respirator (PAPR). Where a PAPR with an integral welding visor is used, the welder is protected when checking their weld without lifting the visor. Where a standard visor is used, welders must wait until all visible fume has cleared before lifting it." },
      { id: 40, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Powered respirators used for welding must have a particulate filter. TH2 filters provide an APF of 20. TH3 filters provide an APF of 40 and should be selected for higher-risk processes such as arc-air gouging lasting less than 30 minutes per shift." },
      { id: 41, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "For arc-air gouging tasks lasting more than 30 minutes per shift, provide airline breathing apparatus (BA) with a welding helmet. Wearers must be assessed as medically fit to wear BA before use." },
      { id: 42, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "For confined space welding where oxygen depletion is possible, provide air-fed RPE with an APF of at least 40. Never use filtering respirators in oxygen-deficient atmospheres - supplied air BA must be used." },
      { id: 43, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Ensure all air supplied to BA meets the minimum quality requirements of the current British Standard. Visually inspect compressed airline hoses for signs of damage before each use." },
      { id: 44, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Face fit testing is mandatory for all tight-fitting RPE. Workers wearing tight-fitting RPE must be clean-shaven and trained in correct donning, doffing, and pre-use checks.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 45, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Where a wearer cannot achieve an adequate fit in a face fit test, select an alternative type of RPE that can be fitted correctly." },
      { id: 46, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Discard disposable RPE at the end of each shift, or sooner if it becomes blocked with fume or dust. Replace reusable respirator filters in accordance with the manufacturer's guidance, and whenever filters are past their shelf-life, visibly damaged or contaminated, or breathing resistance increases." },
      { id: 47, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Carry out thorough examination and testing of non-disposable RPE at least monthly and record the results. Instruct workers to check RPE is functioning correctly before every use." },
      { id: 48, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Keep all RPE clean and store it in a clean, designated location when not in use. Make arrangements for maintenance and timely replacement." },

      // PPE & Skin
      { id: 49, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Provide welders with a welding visor or helmet, flame-resistant overalls, and appropriate protective gloves. Ensure all items of PPE are compatible with each other and with any RPE being worn." },
      { id: 50, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Provide overalls that do not retain dust or fume particles. Arrange laundering through a contract laundry service - workers must not launder work clothing at home." },
      { id: 51, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Keep all PPE clean and replace it at the manufacturer's recommended intervals. Make suitable arrangements for storage and timely replacement." },
      { id: 52, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Provide warm water, mild skin cleansers, and soft paper or fabric towels at all wash stations. Avoid abrasive cleansers." },
      { id: 53, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Provide pre-work emollient creams to make it easier to remove contamination from the skin after work." },
      { id: 54, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Provide after-work emollient creams to restore the natural moisture content of the skin following washing." },
      { id: 55, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Do not use pre-work or 'barrier' creams as a substitute for gloves or other controls - they do not provide a full physical barrier and must only be used alongside appropriate PPE." },
      { id: 56, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Never use brushes or compressed air to remove dust or fume from skin, clothing, or equipment surfaces - these methods disperse contaminants into the breathing zone." },

      // Confined Spaces (WL2)
      { id: 57, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Avoid entry into a confined space to carry out welding or hot work wherever an alternative approach is practicable. If entry is unavoidable, establish a documented safe system of work before any work begins." },
      { id: 58, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Restrict access to the confined space using a permit-to-work system. Before entry, a competent person must assess each worker's suitability, including consideration of claustrophobia and fitness to wear breathing apparatus." },
      { id: 59, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Ensure good air movement and mixing by a suitable means of forced ventilation before and throughout any confined space welding task." },
      { id: 60, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Check the concentration of oxygen in the confined space before entry and monitor the air continuously throughout the work. Never attempt to enrich the atmosphere with oxygen - this increases the risk of fire or explosion." },
      { id: 61, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Carry out toxic and flammable gas and vapour testing before entry and at appropriate intervals during work. Provide personal gas monitors to all workers inside the space for the gases likely to be encountered." },
      { id: 62, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Isolate all mechanical and electrical equipment that could cause harm if it were to start during the work. Ensure safe access and egress routes are adequate for rescue, and that rescue harnesses are appropriate for the space." },
      { id: 63, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Ensure audible alarms are in place and confirmed to be working. Use non-sparking tools and flameproof lighting inside the space. Never use fuelled engines inside or near a confined space - carbon monoxide can accumulate and cause asphyxiation." },
      { id: 64, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Maintain communication between workers inside the confined space and those outside throughout the work. Where multiple workers enter, operate a formal check-in and check-out system." },
      { id: 65, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Establish a written emergency rescue plan specific to the confined space before work starts. The plan must define means of communication between workers and rescuers, rescuer capabilities and training, rescue and resuscitation equipment requirements, and emergency shutdown procedures. Conduct practice drills and update the plan accordingly." },
      { id: 66, cat: "Confined", sec: "Welding in Confined Spaces (WL2)",
        text: "Be aware that welding on the outside of a confined space can ignite materials on the inside in contact with the heated metal. Assess and control this risk before any external hot work begins." },

      // Pressure Blasting - Small Items (WL18)
      { id: 67, cat: "Blast", sec: "Pressure Blasting - Small Items in a Blasting Cabinet (WL18)",
        text: "Use a fully enclosed blasting cabinet kept under negative pressure for all blasting of small items. Consider wet blasting or high-pressure water jetting as lower-dust alternatives to dry abrasive blasting." },
      { id: 68, cat: "Blast", sec: "Pressure Blasting - Small Items in a Blasting Cabinet (WL18)",
        text: "Fit the cabinet with a pressure gauge interlocked with the power supply to prevent operation when extraction is not functioning." },
      { id: 69, cat: "Blast", sec: "Pressure Blasting - Small Items in a Blasting Cabinet (WL18)",
        text: "Ensure a high standard of filtration for air discharged from the cabinet. Discharge extracted air to a safe place outside, away from doors, windows, and air inlets. Run the cabinet extraction for at least two minutes after blasting has ceased to clear residual dust." },

      // Pressure Blasting - Medium Items (WL19)
      { id: 70, cat: "Blast", sec: "Pressure Blasting - Medium Items in a Blasting Booth (WL19)",
        text: "Use a permit-to-work system for access to the blasting booth. Designate the booth an exclusion zone and post clear warning signs. Restrict access to authorised and appropriately trained personnel only." },
      { id: 71, cat: "Blast", sec: "Pressure Blasting - Medium Items in a Blasting Booth (WL19)",
        text: "Use a fully enclosed, extracted blasting booth. Consider wet blasting or high-pressure water jetting as alternatives to dry abrasive blasting, or an automated system. Do not use sand abrasives." },
      { id: 72, cat: "Blast", sec: "Pressure Blasting - Medium Items in a Blasting Booth (WL19)",
        text: "Provide blasting equipment with a fast-actuating cut-off. Fit a pressure gauge or tell-tale to confirm extraction is working, and provide a clean air supply to the workroom to replace extracted air. Confirm extraction is switched on and working before starting every blasting operation." },
      { id: 73, cat: "Blast", sec: "Pressure Blasting - Medium Items in a Blasting Booth (WL19)",
        text: "Provide the blaster with a blasting helmet with airline breathing apparatus (BA). Wearers must be assessed as medically fit to wear BA. Air supplied to BA must meet the minimum quality requirements of the current British Standard." },
      { id: 74, cat: "Blast", sec: "Pressure Blasting - Medium Items in a Blasting Booth (WL19)",
        text: "Provide blast suits, protective gloves, and footwear in addition to BA. Provide coveralls that do not retain dust and arrange laundering through a contract laundry." },
      { id: 75, cat: "Blast", sec: "Pressure Blasting - Medium Items in a Blasting Booth (WL19)",
        text: "Where blasting surfaces coated with old paint, assess for lead content before work begins. If lead-containing paint is present, implement controls in accordance with the Control of Lead at Work Regulations 2002." },

      // Pressure Blasting - Large Items (WL20)
      { id: 76, cat: "Blast", sec: "Pressure Blasting - Large Items (WL20)",
        text: "Wherever possible, carry out blasting of large items in a fully enclosed booth with LEV. Where this is not practicable, use a permit-to-work for access, designate an exclusion zone with barriers and warning signs, and consider scheduling larger jobs at times when fewer people are nearby." },
      { id: 77, cat: "Blast", sec: "Pressure Blasting - Large Items (WL20)",
        text: "Consider wet blasting or high-pressure water jetting as lower-dust alternatives to dry abrasive blasting. Do not use sand abrasives. Provide blasting equipment with a fast-actuating cut-off." },
      { id: 78, cat: "Blast", sec: "Pressure Blasting - Large Items (WL20)",
        text: "Ensure that any assistants working in the blasting area (e.g. kettlemen) are also provided with appropriate RPE - a blasting helmet with airline BA." },
      { id: 79, cat: "Blast", sec: "Pressure Blasting - Large Items (WL20)",
        text: "Provide the blaster with a blasting helmet with airline BA. Maintain all RPE in effective working order, visually inspect compressed airlines before each use, examine and test non-disposable RPE at least monthly, and retain records for at least five years. Wearers must be assessed as medically fit to wear BA." },
      { id: 80, cat: "Blast", sec: "Pressure Blasting - Large Items (WL20)",
        text: "Provide blast suits, protective gloves, footwear, and dust-retaining coveralls for all blasting workers. Arrange laundering through a contract laundry." },
      { id: 81, cat: "Blast", sec: "Pressure Blasting - Large Items (WL20)",
        text: "Where blasting surfaces coated with old paint, assess for lead content before work begins. If lead-containing paint is present, implement controls in accordance with the Control of Lead at Work Regulations 2002." },
      { id: 82, cat: "Blast", sec: "Pressure Blasting - Large Items (WL20)",
        text: "Do not use dry brushing to clean up blasting dust. Use damp cleaning methods wherever possible." },

      // Pickling Paste (WL21)
      { id: 83, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Consider substituting pickling paste with alternative post-weld cleaning methods such as mechanical grinding or electrochemical cleaning, which eliminate the risk of acid burns and toxic inhalation." },
      { id: 84, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Where pickling paste must be used, select the product with the lowest practicable acid concentration or highest viscosity to reduce splash and vapour generation." },
      { id: 85, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Provide a good standard of general ventilation in all areas where pickling paste is applied. Never use pickling pastes in confined spaces." },
      { id: 86, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Apply pickling paste by brush only - never by roller or spray. Avoid paste spraying in all circumstances." },
      { id: 87, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Buy paste in appropriately sized containers to match usage. Do not store far more than needed and avoid decanting between containers." },
      { id: 88, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Remove surplus paste with a damp cloth and discard it immediately to a sealed contaminated waste container. Store and dispose of all hazardous waste safely and in accordance with environmental regulations." },
      { id: 89, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Provide chemical-resistant nitrile gloves, eye protection, overalls, and footwear for all pickling paste work. Replace damaged gloves immediately and ensure all PPE is compatible with other equipment in use." },
      { id: 90, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Do not use pre-work or 'barrier' creams as a substitute for chemical-resistant gloves - they do not provide a full physical barrier." },
      { id: 91, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Ensure adequate first aid provisions are available at all times when pickling pastes containing hydrofluoric acid (HF) are in use. Stock calcium gluconate gel on site. In the event of HF skin contact, wash immediately with large amounts of running water, apply calcium gluconate gel to the affected area, and continue massaging it into the skin until the worker receives hospital medical attention." },
      { id: 92, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Instruct workers to wash hands and face after using pickling pastes and before eating, drinking, smoking, or using toilet facilities." },
      { id: 93, cat: "Pickling", sec: "Weld Cleaning with Pickling Paste (WL21)",
        text: "Implement a health surveillance programme for occupational dermatitis where workers have regular skin contact with pickling paste. Surveillance should include pre-placement skin assessment and regular periodic skin inspections, with referral to occupational health if symptoms are identified.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },

      // Maintenance, Examination & Testing
      { id: 94, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Ensure all LEV systems are commissioned when first installed. Commissioning establishes the design specification, confirms fume control performance, and provides the baseline data required for ongoing examination and testing." },
      { id: 95, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Keep all LEV and associated equipment in effective working order. Before starting work each day, check for signs of damage and confirm that airflow indicators show correct airflow. Carry out daily visual checks for noisy or vibrating fans, which may indicate a fault." },
      { id: 96, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Maintain an LEV user manual and logbook recording operating specifications, maintenance schedules, and records of all checks, maintenance, and repairs. If the system was installed without documentation, commission a competent person to carry out a system assessment and produce a commissioning report." },
      { id: 97, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "LEV systems are subject to a statutory Thorough Examination and Test (TExT) at intervals not exceeding 14 months. Carry out all remedial actions identified by TExT reports without undue delay and retain records for at least 5 years.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 98, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Carry out weekly visual checks that all LEV systems are working correctly and record these in the logbook." },

      // Cleaning & Housekeeping
      { id: 100, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Keep all work areas clean and free of combustible materials at all times." },
      { id: 101, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Never use brushes or compressed air to remove dust from skin, clothing, surfaces, or inside machinery - these methods disperse fume and dust particles into the breathing zone." },
      { id: 102, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Provide clean welfare facilities for washing and taking refreshment, located away from all welding and hot work activities. Instruct workers to wash hands and face before eating, drinking, smoking, or using toilet facilities." },

      // Health Surveillance
      { id: 103, cat: "Health", sec: "Health Surveillance",
        text: "Implement a health surveillance programme for occupational asthma where workers are regularly exposed to welding fume, particularly when welding metals that generate respiratory sensitisers such as stainless steel (chromium and nickel compounds). Surveillance must be conducted under the supervision of a doctor or occupational health professional and should include pre-placement baseline assessment, periodic symptom questionnaires, and lung function testing (spirometry).",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },

      // Training & Supervision
      { id: 104, cat: "Train", sec: "Training & Supervision",
        text: "Permit access to welding and hot work areas to authorised and appropriately trained personnel only." },
      { id: 105, cat: "Train", sec: "Training & Supervision",
        text: "Provide documented training covering: the health hazards of welding fume, cutting fume, shielding gases, and pickling paste; correct use and positioning of LEV for each welding process; correct use, fitting, maintenance, and storage of RPE and PPE; how to recognise early signs of occupational asthma and dermatitis; and actions to take in the event of a control failure or chemical contact." },
      { id: 106, cat: "Train", sec: "Training & Supervision",
        text: "For confined space welding, provide specific training covering: the safe system of work and permit-to-work procedure, the particular hazards of the confined space, the use of gas monitoring equipment and personal gas monitors, the correct use of forced ventilation and breathing apparatus, and emergency rescue procedures." },
      { id: 107, cat: "Train", sec: "Training & Supervision",
        text: "For abrasive blasting, provide specific training on the correct use of the blasting booth LEV, the blasting helmet and airline BA, and what to do if controls fail or equipment is damaged." },
      { id: 108, cat: "Train", sec: "Training & Supervision",
        text: "Maintain training records as evidence that training has been delivered and understood. Include managers and supervisors in all relevant training." },
      { id: 109, cat: "Train", sec: "Training & Supervision",
        text: "Provide active supervision to ensure safe work procedures are consistently followed, and review and update training whenever processes, substances, or equipment change." },
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // WOOD DUST
  // Sources: WD1 (bandsaw), WD2 (circular bench saw), WD3 (cross-cut saw),
  //          WD4 (vertical spindle moulder), WD5 (routers), WD7 (hand-held
  //          powered sanders), WD10 (wall saw), WD11 (surface planer),
  //          WD12 (narrow belt sanding machines), WD13 (disc sanding machines),
  //          WD14 (drum/bobbin sanding machines), WD15 (chop saw),
  //          WD17 (suction hose cleaning)
  // ═══════════════════════════════════════════════════════════════════════════
  wood: {
    label: "Wood Dust",
    cats: [
      { id: "all",    label: "All" },
      { id: "LEV",    label: "LEV & Engineering" },
      { id: "RPE",    label: "RPE" },
      { id: "PPE",    label: "PPE & Skin" },
      { id: "Maint",  label: "Maintenance" },
      { id: "Clean",  label: "Cleaning" },
      { id: "Health", label: "Health surv." },
      { id: "Train",  label: "Training" },
    ],
    items: [

      // ── LEV & Engineering Controls ─────────────────────────────────────────
      { id: 1,  cat: "LEV", sec: "LEV & Engineering Controls",
        text: "Restrict access to all woodworking areas to authorised and appropriately trained personnel only." },
      { id: 2,  cat: "LEV", sec: "LEV & Engineering Controls",
        text: "Fit efficient dust extraction (local exhaust ventilation - LEV) at the source of dust generation on every woodworking machine. Extraction must be in operation whenever the machine is in use." },
      { id: 3,  cat: "LEV", sec: "LEV & Engineering Controls",
        text: "Airflow must be sufficient to capture airborne wood dust effectively at every machine. Volume flow rates (VFRs) should be confirmed against the machine manufacturer's specification or, where this is unavailable, against published ACGIH industrial ventilation data." },
      { id: 4,  cat: "LEV", sec: "LEV & Engineering Controls",
        text: "Keep extraction systems as simple and direct as possible - minimise the use of flexible ducting and use rigid ductwork wherever practicable." },
      { id: 5,  cat: "LEV", sec: "LEV & Engineering Controls",
        text: "Ensure all connections between flexible ducts and machine hoods are secure and airtight." },
      { id: 6,  cat: "LEV", sec: "LEV & Engineering Controls",
        text: "Position woodworking operations away from doors, windows, and walkways wherever possible to prevent draughts from disrupting LEV airflow and dispersing dust into the workplace." },
      { id: 7,  cat: "LEV", sec: "LEV & Engineering Controls",
        text: "Provide a means of confirming that LEV is working correctly before work starts on each machine - for example, an airflow indicator or equivalent device." },
      { id: 8,  cat: "LEV", sec: "LEV & Engineering Controls",
        text: "Provide adequate clean make-up air into the workplace to replace the volume of air extracted by LEV systems." },

      // ── Machine-specific LEV ───────────────────────────────────────────────
      { id: 9,  cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Bandsaw: fit LEV at low level to the rear of the machine casing. Where this alone is insufficient, add under-table extraction or a moveable hood positioned above the table. Ensure any access doors into the machine casing remain closed during operation and that all rubber seals are maintained in good condition." },
      { id: 10, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Circular bench saw: fit LEV to both the top (crown) guard and beneath the bench. To maximise extraction efficiency through the top guard, minimise flexible ducting, use rigid ductwork wherever possible, and fit an expansion piece (such as a funnel) to the extract port. Design and fit an effective under-bench enclosure to capture dust emitted below the bench, and ensure a continuous air supply is provided where the saw motor is enclosed within the hood to prevent dust accumulation and fire/explosion risk." },
      { id: 11, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Cross-cut saw: fit LEV to the top guard and to an extracted hood positioned behind the saw, as dust is typically projected towards the rear of the machine. Design the hood to suit the dimensions of pieces being cut. Where wider workpieces are cut or angled cuts are made, add hinged side screens and flexible seals to intercept the dust cloud and increase the volume flow rate at the hood inlet accordingly. Fit an air flow indicator to the connecting ductwork." },
      { id: 12, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Vertical spindle moulder: position exhaust hoods behind the cutter guard, behind the fence (in line with the workpiece), and above the motor. Ensure make-up air can enter the LEV system - a continuous airflow is particularly important if the cutter motor is located within the top hood to prevent dust build-up and fire/explosion risk." },
      { id: 13, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Routers - hand-held: fit on-tool extraction with a transparent viewing panel and brush seal around the router head. Do not remove the viewing panel during use, as this renders the extraction ineffective. Use a dust extraction unit of at least dust Class M (medium hazard) classification and ensure the extraction hose is properly connected using an adaptor - not tape." },
      { id: 14, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Routers - overhead fixed: enclose the router head and fit the enclosure with dust extraction." },
      { id: 15, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Routers - CNC flat-bed: enclose the router head, fit dust extraction to the enclosure, and operate the router remotely. Check the dust collection system regularly and empty as required." },
      { id: 16, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Hand-held powered sanders: use on-tool dust extraction of at least dust Class M (medium hazard) classification. Ensure the extraction hose is properly connected using an adaptor - not tape. Position the sander as close as possible to the work surface to maximise contact and minimise dust escape. Use sanding materials that allow air to pass through them; where extracted sanding discs are used, align the extraction holes accurately. Check the dust collection system regularly and empty as required - where dust is collected in waste bags, use appropriate disposable bags and do not empty and reuse them." },
      { id: 17, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Wall saw: fit LEV around the blade to capture wood dust. Take account of the blade movement, which generates air currents stronger than LEV airflow and tends to drive dust horizontally along the backboard - hood design must account for this. Segregate the backboard area from the operator's working zone and minimise the time any worker spends in the backboard area during operation." },
      { id: 18, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Surface planer: fit LEV below the working surface of the machine. Enclose and extract the cutter beneath the bench to capture emitted dust. Where the machine has no top hood, LEV must be fitted at low level only." },
      { id: 19, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Narrow belt sanding machines - large horizontal pad sanders: enclose the head pulley and tail pulley with LEV hoods, extending across the top of the machine where sanding is performed on the top run. Carry out sanding close to the LEV hood inlet. Fit additional in-table LEV near the sanding position if control is difficult. Use flanges on extraction inlets to improve dust capture." },
      { id: 20, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Narrow belt sanding machines - vertical belt sanders (linishers): site work close to the head pulley to make best use of LEV. Where dust is released as the belt leaves the main hood, intercept it using a downdraught grille or supplementary LEV hood. Enclose the sides of the belt as much as the nature of the workpiece allows." },
      { id: 21, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Disc sanding machines: fit an annular LEV hood around the sanding disc and, where possible, add extraction through the worktable. Use flanges on extraction inlets to improve dust capture. Where the sanding head movement counteracts extraction, enclose the sanding surface as much as practicable. For heavy-duty or large-workpiece sanding, enclose the machine in an exhaust-ventilated booth." },
      { id: 22, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Drum/bobbin sanding machines: fit LEV around the sanding drum, using hoods that enclose the drum as fully as practicable. Use flanges on extraction inlets to improve dust capture. Where the sanding belt motion counteracts LEV, consider directing an air jet onto the belt just before it exits the extraction hood to dislodge adhered dust. Anti-static abrasive belts may help where static electricity is causing dust to cling to the abrasive surface." },
      { id: 23, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Chop saw: fit LEV to the top guard and fit an extracted hood behind the saw to capture dust projected rearwards. Fit hinged side screens and flexible seals where needed to intercept the dust cloud. Fit an expansion piece to the top guard extract port to increase the opening size and improve the volume flow rate. Use rigid ductwork in preference to flexible wherever possible." },
      { id: 24, cat: "LEV", sec: "Machine-specific LEV Requirements",
        text: "Note that the movement of the sanding head on disc and drum/bobbin sanding machines often produces air currents strong enough to counteract extraction - where this is the case, enclosing the sanding surface more fully and increasing the volume flow rate are the primary remedies." },

      // ── RPE ───────────────────────────────────────────────────────────────
      { id: 25, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "RPE with a UK Standard Assigned Protection Factor (APF) of at least 20 is required for all tasks where LEV alone cannot adequately control wood dust exposure. Suitable options include an FFP3 disposable mask, a half mask with a P3 filter, or a powered respirator (e.g. TH2 powered hood/helmet). RPE is supplementary to - not a substitute for - LEV." },
      { id: 26, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "RPE must be worn during maintenance and cleaning of all woodworking machines and LEV systems, not only during active machining." },
      { id: 27, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Where tight-fitting RPE is used (e.g. FFP3 or half-mask), face fit testing is mandatory. Workers wearing tight-fitting RPE must be clean-shaven and trained in how to fit, wear, and care for the equipment correctly.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 28, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Disposable RPE must be discarded at the end of each shift, or sooner if it becomes blocked or breathing resistance increases." },
      { id: 29, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Replace reusable respirator filters in accordance with the manufacturer's guidance and whenever filters are past their shelf-life, visibly damaged or contaminated, or breathing resistance increases." },
      { id: 30, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Thoroughly examine and test non-disposable RPE at least once every month. Workers must check that RPE is functioning correctly before every use. Maintain records of all examination, testing, and pre-use checks." },
      { id: 31, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Where RPE is required for extended periods (more than one hour of continuous use), provide powered respirators or constant-flow airline breathing apparatus." },
      { id: 32, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Make suitable provision for the maintenance, storage, and replacement of all RPE. Keep RPE clean and store it in a clean, designated location when not in use." },
      { id: 33, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "For overhead fixed routers and powered hand-held routers fitted with on-tool extraction, RPE is normally required even where engineering controls are in place - the nature of these operations means residual dust exposure above acceptable levels is common." },
      { id: 34, cat: "RPE", sec: "Respiratory Protective Equipment",
        text: "Where any woodworking task requires continuous RPE use for more than one hour, tight-fitting masks are likely to become uncomfortable - provide powered respirators with an equivalent protection level (e.g. TH2 hood or helmet) for these tasks." },

      // ── PPE & Skin ────────────────────────────────────────────────────────
      { id: 35, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Provide coveralls that do not retain dust for all woodworking personnel. Arrange laundering through a contract laundry service - workers must not launder contaminated work clothing at home." },
      { id: 36, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Where gloves are required to control the risk of dermatitis, select gloves that are also suitable for the safety risks of the specific task - for machine operations involving rotating parts, gloves must be designed to disintegrate and detach from the hand if they become entangled, to prevent draw-in injuries. Where entanglement risk is significant (e.g. hand-held routing or sanding), gloves should not be worn." },
      { id: 37, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Workers must change and discard damaged gloves immediately. Make suitable provision for the maintenance, storage, and replacement of all PPE." },
      { id: 38, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Provide warm water, mild skin cleansers, and soft paper or fabric towels at all wash stations. Avoid abrasive cleansers." },
      { id: 39, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Provide pre-work emollient skin creams to make it easier to remove contamination from the skin after work." },
      { id: 40, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Provide after-work emollient creams to replenish skin moisture following handwashing." },
      { id: 41, cat: "PPE", sec: "PPE & Skin Protection",
        text: "Do not use pre-work or barrier creams as a substitute for gloves - they do not provide a complete physical barrier and must only be used alongside appropriate PPE." },

      // ── Maintenance, Examination & Testing ────────────────────────────────
      { id: 42, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Keep all woodworking machines and associated LEV systems in effective working order. Maintain all equipment in accordance with the supplier's or installer's guidance." },
      { id: 43, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Before starting work each day, check all control equipment for signs of damage and confirm that airflow indicators show correct airflow. Do not operate a machine where LEV is damaged or not functioning correctly." },
      { id: 44, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Maintain an LEV user manual or logbook for each extraction system, setting out performance specifications, checking frequency, maintenance schedules, and parts replacement history. Where no user manual exists, a competent person must assess the system and establish these parameters." },
      { id: 45, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "All LEV systems are subject to a statutory Thorough Examination and Test (TExT) carried out by a competent person at intervals not exceeding 14 months. Carry out all remedial actions arising from TExT reports without undue delay.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 46, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Retain records of all LEV examinations and tests - including target extraction rates that demonstrate the system is performing as originally commissioned - for a minimum of 5 years." },
      { id: 47, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "On-tool extraction systems on hand-held routers and sanders must also undergo a statutory TExT. Each examination should include: a visual check of the extraction system for damage or cracks, confirmation that velocity in the extraction hose exceeds 20 m/s, a functional check of the flow indicator by simulating reduced airflow, and inspection of the filter and filter seal for damage by checking for dust downstream of the filter.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 48, cat: "Maint", sec: "Maintenance, Examination & Testing",
        text: "Verify the effectiveness of controls using qualitative dust lamp (Tyndall beam) checks to identify leaks and areas of high dust concentration.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },

      // ── Cleaning & Housekeeping ────────────────────────────────────────────
      { id: 49, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Clean all woodworking machines and the immediate work area at the end of each shift (daily minimum). Clean other equipment and the wider workroom, including overhead surfaces, at least once per week." },
      { id: 50, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Remove wood dust using vacuum equipment that meets at least the dust Class M (medium hazard) classification. A suction hose attachment fitted to the machine's own LEV system is an equally effective and cost-efficient alternative for floor cleaning." },
      { id: 51, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Never use brushes or compressed air to remove wood dust from skin, clothing, machine surfaces, or the inside of machinery - these methods disperse dust particles into the breathing zone and worsen exposure." },
      { id: 52, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Wood dust waste - including paint debris, contaminated PPE, and disposable materials - must be collected promptly, double-bagged, clearly labelled, and disposed of as hazardous waste in accordance with environmental regulations." },
      { id: 53, cat: "Clean", sec: "Cleaning & Housekeeping",
        text: "Where a suction hose attachment is used for floor cleaning with the machine's own LEV system, ensure the hose is at least 100 mm in diameter to prevent blockage by wood chips and that all connections to the LEV system are secure and airtight." },

      // ── Health Surveillance ────────────────────────────────────────────────
      { id: 54, cat: "Health", sec: "Health Surveillance",
        text: "Implement a health surveillance programme for occupational asthma where workers are regularly exposed to wood dust. Hardwood dust is a recognised respiratory sensitiser and can cause occupational asthma and nasal cancer - surveillance is required where there is a reasonable likelihood of asthma developing. The programme must be conducted under the supervision of a doctor or occupational health professional and should include pre-placement baseline assessment, periodic symptom questionnaires, and lung function testing (spirometry).",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 55, cat: "Health", sec: "Health Surveillance",
        text: "Implement a health surveillance programme for occupational dermatitis where workers have regular skin contact with wood dust or wood materials. The dermatitis risk is particularly high for softwoods. Surveillance should include pre-placement skin assessment and regular periodic skin inspections, with referral to occupational health if symptoms are identified.",
        upsell: "Synergy Environmental Solutions can offer this service for you. Please contact us for further information." },
      { id: 56, cat: "Health", sec: "Health Surveillance",
        text: "Inform workers of the early signs and symptoms of occupational asthma and contact dermatitis and instruct them to report any symptoms to their line manager promptly." },
      { id: 57, cat: "Health", sec: "Health Surveillance",
        text: "Workers must co-operate with all health surveillance requirements, including pre-placement assessments, periodic examinations, and any additional assessments requested following a reported symptom." },

      // ── Training & Supervision ─────────────────────────────────────────────
      { id: 58, cat: "Train", sec: "Training & Supervision",
        text: "Provide documented training for all woodworking personnel covering: the health hazards of wood dust (asthma, dermatitis, nasal cancer) and how to recognise early signs of these conditions; correct operation, checking, and limitations of LEV on each machine they operate; correct use, fitting, maintenance, and storage of RPE and PPE; how to check that LEV and RPE are working correctly before each use; and the actions to take if controls are found to be faulty or insufficient." },
      { id: 59, cat: "Train", sec: "Training & Supervision",
        text: "Maintain training records as evidence that training has been delivered and understood. Include managers and supervisors in all relevant health and safety training." },
      { id: 60, cat: "Train", sec: "Training & Supervision",
        text: "Provide active supervision to ensure safe working procedures are consistently followed, and implement a formal procedure to check that all control measures are in place and functioning at the start of each working period." },
      { id: 61, cat: "Train", sec: "Training & Supervision",
        text: "Review and update training whenever work processes, materials, LEV systems, or equipment change." },
    ]
  }

};

// ─────────────────────────────────────────────────────────────────────────────
// Legacy alias - keeps taskpane.html (flour-only builds) working if needed
// ─────────────────────────────────────────────────────────────────────────────
const RECOMMENDATIONS = RECOMMENDATIONS_DATA.flour.items;
